# Bisq Payment Method Popularity Chart
set title "Bisq Payment Method Popularity"
set xlabel "Payment Method"
set ylabel "Total Trades (Log Base 10 Scale)"
set terminal png size 3840,2160
set output 'Plots\\PaymentMethodPopularity.png'
set format y '%.0f'
set logscale y 10
set xtics rotate by 45 right
set offset 0.5
set yrange [0:*]
plot "Data\\PaymentMethods.dat" using 2:xtic(1) with boxes title "Payment Method Total Trades"