IF OBJECT_ID ('dbo.tx') IS NULL 
	CREATE TABLE dbo.tx (
		Id BIGINT NOT NULL PRIMARY KEY,
		Hash VARCHAR(64) NOT NULL,
		Version TINYINT NOT NULL,
		LockTime BIGINT NOT NULL,
		BisqType TINYINT NOT NULL,
		BisqProposalAccepted TINYINT,
		BlockId BIGINT FOREIGN KEY REFERENCES block(Id) NOT NULL
	)