IF OBJECT_ID ('dbo.txIn') IS NULL 
	CREATE TABLE dbo.txIn (
		Id BIGINT NOT NULL PRIMARY KEY,
		ScriptSig VARBINARY(200),
		SeqNum BIGINT NOT NULL,
		TxId BIGINT FOREIGN KEY REFERENCES tx(Id) NOT NULL,
		TxOutId BIGINT FOREIGN KEY REFERENCES txOut(Id)
	)